name: Build and test library

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build and test library
    uses: zig-devel/.github/.github/workflows/library.yml@latest
