name: Prepare GH release

on:
  push:
    tags: [ '*.*.*-*' ]

jobs:
  release:
    name: Prepare GitHub release
    uses: zig-devel/toolset/.github/workflows/_release.yml@latest
    permissions:
      contents: write
